' ******************************************************************************
' Startup
'
' 27 Mar 2019
' v1.0
'

'define constants
' Clear existing constants
CONSTANT

'Communication default output channel
CONSTANT "comms",5

'Define Message levels
CONSTANT "msg_none",$0
CONSTANT "msg_errors",$1
CONSTANT "msg_warnings",$2
CONSTANT "msg_info",$4
CONSTANT "msg_trace",$8



CONSTANT "startup_completed",TRUE
